let
    Source = SharePoint.Files("https://uonstaff.sharepoint.com/sites/", [ApiVersion = 15]),
    #"Filtered Rows1" = Table.SelectRows(Source, each ([Extension] = ".xlsx") and ([Name] = "WL-PowerBI Data.xlsx")),
    #"WL-PowerBI Data xlsx_https://uonstaff sharepoint com/sites/" = #"Filtered Rows1"{[Name="WL-PowerBI Data.xlsx",#"Folder Path"="https://uonstaff.sharepoint.com/sites/HCISS/Shared Documents/T&L/WorkloadCommittee/Forecasts/"]}[Content],
    #"Imported Excel Workbook" = Excel.Workbook(#"WL-PowerBI Data xlsx_https://uonstaff sharepoint com/sites/"),
    #"HCISS course data_Sheet" = #"Imported Excel Workbook"{[Item="Course data",Kind="Sheet"]}[Data],
    #"Promoted Headers" = Table.PromoteHeaders(#"HCISS course data_Sheet", [PromoteAllScalars=true]),
    #"Replaced Value" = Table.ReplaceValue(#"Promoted Headers","NCL","Newcastle City",Replacer.ReplaceText,{"Location"}),
    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","CAL","Callaghan",Replacer.ReplaceText,{"Location"}),
    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","ONL","Online",Replacer.ReplaceText,{"Location"}),
    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","OUR","Ourimbah",Replacer.ReplaceText,{"Location"}),
    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","SEM1","Semester 1",Replacer.ReplaceText,{"Term"}),
    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","SEM2","Semester 2",Replacer.ReplaceText,{"Term"}),
    #"Replaced Value6" = Table.ReplaceValue(#"Replaced Value5","SUM2","Summer 2",Replacer.ReplaceText,{"Term"}),
    #"Replaced Value7" = Table.ReplaceValue(#"Replaced Value6","SUM1","Summer 1",Replacer.ReplaceText,{"Term"}),
    #"Replaced Value8" = Table.ReplaceValue(#"Replaced Value7","WINT","Winter",Replacer.ReplaceText,{"Term"}),
    #"Replaced Value9" = Table.ReplaceValue(#"Replaced Value8","TRI1","Trimester 1",Replacer.ReplaceText,{"Term"}),
    #"Replaced Value10" = Table.ReplaceValue(#"Replaced Value9","TRI2","Trimester 2",Replacer.ReplaceText,{"Term"}),
    #"Replaced Value11" = Table.ReplaceValue(#"Replaced Value10","TRI3","Trimester 3",Replacer.ReplaceText,{"Term"}),
    #"Replaced Value12" = Table.ReplaceValue(#"Replaced Value11","Q1","Quarter 1",Replacer.ReplaceText,{"Term"}),
    #"Replaced Value13" = Table.ReplaceValue(#"Replaced Value12","Q2","Quarter 2",Replacer.ReplaceText,{"Term"}),
    #"Replaced Value14" = Table.ReplaceValue(#"Replaced Value13","Q3","Quarter 3",Replacer.ReplaceText,{"Term"}),
    #"Replaced Value15" = Table.ReplaceValue(#"Replaced Value14","Q4","Quarter 4",Replacer.ReplaceText,{"Term"}),
    #"Changed Type3" = Table.TransformColumnTypes(#"Replaced Value15",{{"Year", type text}}),
    #"Inserted Merged Column" = Table.AddColumn(#"Changed Type3", "Key", each Text.Combine({[Course Code], [Term], [Location], [Year]}, "-"), type text),
    #"Replaced Errors1" = Table.ReplaceErrorValues(#"Inserted Merged Column", {{"% variance allocation to weighting", 0}}),
    #"Filtered Rows" = Table.SelectRows(#"Replaced Errors1", each ([Course Code] <> null)),
    #"Renamed Columns" = Table.RenameColumns(#"Filtered Rows",{{"Staff Mapping Notes (e.g. please provide a summary of team teaching if needed as per team teaching XLS calculators, any Casual staff expected, new course project allocations and any other relevant details)", "Notes"}, {"Core, Comp, Dirctd", "Core, Compulsory, Directed"}}),
    #"Replaced Value16" = Table.ReplaceValue(#"Renamed Columns",null,0,Replacer.ReplaceValue,{"Actual Census Enrols"}),
    #"Changed Type" = Table.TransformColumnTypes(#"Replaced Value16",{{"Proposed Coordinator - allocation", type number}, {"Team Teaching Contributor 1 allocation", type number}, {"Team Teaching Contributor 2 allocation", type number}, {"Team Teaching Contributor 3 allocation", type number}, {"Team Teaching Contributor 4 allocation", type number}, {"Team Teaching Contributor 5 allocation", type number}, {"Team Teaching Contributor 6 allocation", type number}, {"Team Teaching Contributor 7 allocation", type number}, {"Team Teaching Contributor 8 allocation", type number}, {"Team Teaching Contributor 9 allocation", type number}, {"Team Teaching Contributor 10 allocation", type number}, {"Team Teaching Contributor 11 allocation", type number}, {"Team Teaching Contributor 12 allocation", type number}, {"Team Teaching Contributor 13 allocation", type number}, {"Team Teaching Contributor 14 allocation", type number}, {"% Casual Staffing Forecast", type number}}),
    #"Added Custom" = Table.AddColumn(#"Changed Type", "Total WL %", each (List.Sum({
    if [#"Proposed Coordinator - allocation"] = null then 0 else [#"Proposed Coordinator - allocation"],
    if [Team Teaching Contributor 1 allocation] = null then 0 else [Team Teaching Contributor 1 allocation],
    if [Team Teaching Contributor 2 allocation] = null then 0 else [Team Teaching Contributor 2 allocation],
    if [Team Teaching Contributor 3 allocation] = null then 0 else [Team Teaching Contributor 3 allocation],
    if [Team Teaching Contributor 4 allocation] = null then 0 else [Team Teaching Contributor 4 allocation],
    if [Team Teaching Contributor 5 allocation] = null then 0 else [Team Teaching Contributor 5 allocation],
    if [Team Teaching Contributor 6 allocation] = null then 0 else [Team Teaching Contributor 6 allocation],
    if [Team Teaching Contributor 7 allocation] = null then 0 else [Team Teaching Contributor 7 allocation],
    if [Team Teaching Contributor 8 allocation] = null then 0 else [Team Teaching Contributor 8 allocation],
    if [Team Teaching Contributor 9 allocation] = null then 0 else [Team Teaching Contributor 9 allocation],
    if [Team Teaching Contributor 10 allocation] = null then 0 else [Team Teaching Contributor 10 allocation],
    if [Team Teaching Contributor 11 allocation] = null then 0 else [Team Teaching Contributor 11 allocation], 
    if [Team Teaching Contributor 12 allocation] = null then 0 else [Team Teaching Contributor 12 allocation],
    if [Team Teaching Contributor 13 allocation] = null then 0 else [Team Teaching Contributor 13 allocation],
    if [Team Teaching Contributor 14 allocation] = null then 0 else [Team Teaching Contributor 14 allocation]
}))/100),
    #"Added Custom1" = Table.AddColumn(#"Added Custom", "Discipline", each null),
    #"Removed Columns2" = Table.RemoveColumns(#"Added Custom1",{"Forecast Course size", "Forecast Base course (value) % allocated", "Forecast overall course (value) % allocation", "% variance allocation to weighting", "% Casual Staffing Forecast"}),
    #"Added Conditional Column" = Table.AddColumn(#"Removed Columns2", "Forecast Course size", each if [Forecast Enrols] <= 34 then "Small" else if [Forecast Enrols] <= 74 then "Medium" else if [Forecast Enrols] <= 299 then "Large" else if [Forecast Enrols] >= 300 then "X-Large" else "Unknown"),
    #"Added Conditional Column1" = Table.AddColumn(#"Added Conditional Column", "Forecast Base course (value) % allocated", each if [#"Forecast Course size"] = "Small" then 5 else if [#"Forecast Course size"] = "Medium" then 10 else if [#"Forecast Course size"] = "Large" then 20 else if [#"Forecast Course size"] = "X-Large" then 30 else "Unknown"),
    #"Added Custom2" = Table.AddColumn(#"Added Conditional Column1", "Forecast overall course (value) % allocation", each [#"Forecast Base course (value) % allocated"]*[MULTIPLIER]),
    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom2",{{"Forecast Base course (value) % allocated", type number}, {"Forecast overall course (value) % allocation", type number}, {"% change if required at census", type number}}),
    #"Added Custom3" = Table.AddColumn(#"Changed Type1", "% variance allocation to weighting", 
     each ((if [Team Teaching Contributor 14 allocation] = null then 0 else [Team Teaching Contributor 14 allocation]) + 
         (if [Team Teaching Contributor 13 allocation] = null then 0 else [Team Teaching Contributor 13 allocation]) + 
         (if [Team Teaching Contributor 12 allocation] = null then 0 else [Team Teaching Contributor 12 allocation]) + 
         (if [Team Teaching Contributor 11 allocation] = null then 0 else [Team Teaching Contributor 11 allocation]) + 
         (if [Team Teaching Contributor 10 allocation] = null then 0 else [Team Teaching Contributor 10 allocation]) + 
         (if [Team Teaching Contributor 9 allocation] = null then 0 else [Team Teaching Contributor 9 allocation]) + 
         (if [Team Teaching Contributor 8 allocation] = null then 0 else [Team Teaching Contributor 8 allocation]) + 
         (if [Team Teaching Contributor 7 allocation] = null then 0 else [Team Teaching Contributor 7 allocation]) + 
         (if [Team Teaching Contributor 6 allocation] = null then 0 else [Team Teaching Contributor 6 allocation]) + 
         (if [Team Teaching Contributor 5 allocation] = null then 0 else [Team Teaching Contributor 5 allocation]) + 
         (if [Team Teaching Contributor 4 allocation] = null then 0 else [Team Teaching Contributor 4 allocation]) + 
         (if [Team Teaching Contributor 3 allocation] = null then 0 else [Team Teaching Contributor 3 allocation]) + 
         (if [Team Teaching Contributor 2 allocation] = null then 0 else [Team Teaching Contributor 2 allocation]) + 
         (if [Team Teaching Contributor 1 allocation] = null then 0 else [Team Teaching Contributor 1 allocation]) + 
         (if [#"Proposed Coordinator - allocation"] = null then 0 else [#"Proposed Coordinator - allocation"]) - 
         (if [#"Forecast overall course (value) % allocation"] = null then 0 else [#"Forecast overall course (value) % allocation"])-
         (if [#"% change if required at census"] = null then 0 else [#"% change if required at census"]))
    ),
#"Added Custom 5" = Table.AddColumn(#"Added Custom3", "% Casual Staffing Forecast", 
        each 
        let
            CasualAllocations = [
                ProposedCoordinator = if Record.HasFields(_, "Proposed Coordinator") and _[Proposed Coordinator] = "Casual" then _[#"Proposed Coordinator - allocation"] else 0,
                Contributor1 = if Record.HasFields(_, "Team Teaching Contributor 1") and _[Team Teaching Contributor 1] = "Casual" then _[#"Team Teaching Contributor 1 allocation"] else 0,
                Contributor2 = if Record.HasFields(_, "Team Teaching Contributor 2") and _[Team Teaching Contributor 2] = "Casual" then _[#"Team Teaching Contributor 2 allocation"] else 0,
                Contributor3 = if Record.HasFields(_, "Team Teaching Contributor 3") and _[Team Teaching Contributor 3] = "Casual" then _[#"Team Teaching Contributor 3 allocation"] else 0,
                Contributor4 = if Record.HasFields(_, "Team Teaching Contributor 4") and _[Team Teaching Contributor 4] = "Casual" then _[#"Team Teaching Contributor 4 allocation"] else 0,
                Contributor5 = if Record.HasFields(_, "Team Teaching Contributor 5") and _[Team Teaching Contributor 5] = "Casual" then _[#"Team Teaching Contributor 5 allocation"] else 0,
                Contributor6 = if Record.HasFields(_, "Team Teaching Contributor 6") and _[Team Teaching Contributor 6] = "Casual" then _[#"Team Teaching Contributor 6 allocation"] else 0,
                Contributor7 = if Record.HasFields(_, "Team Teaching Contributor 7") and _[Team Teaching Contributor 7] = "Casual" then _[#"Team Teaching Contributor 7 allocation"] else 0,
                Contributor8 = if Record.HasFields(_, "Team Teaching Contributor 8") and _[Team Teaching Contributor 8] = "Casual" then _[#"Team Teaching Contributor 8 allocation"] else 0,
                Contributor9 = if Record.HasFields(_, "Team Teaching Contributor 9") and _[Team Teaching Contributor 9] = "Casual" then _[#"Team Teaching Contributor 9 allocation"] else 0,
                Contributor10 = if Record.HasFields(_, "Team Teaching Contributor 10") and _[Team Teaching Contributor 10] = "Casual" then _[#"Team Teaching Contributor 10 allocation"] else 0,
                Contributor11 = if Record.HasFields(_, "Team Teaching Contributor 11") and _[Team Teaching Contributor 11] = "Casual" then _[#"Team Teaching Contributor 11 allocation"] else 0,
                Contributor12 = if Record.HasFields(_, "Team Teaching Contributor 12") and _[Team Teaching Contributor 12] = "Casual" then _[#"Team Teaching Contributor 12 allocation"] else 0,
                Contributor13 = if Record.HasFields(_, "Team Teaching Contributor 13") and _[Team Teaching Contributor 13] = "Casual" then _[#"Team Teaching Contributor 13 allocation"] else 0,
                Contributor14 = if Record.HasFields(_, "Team Teaching Contributor 14") and _[Team Teaching Contributor 14] = "Casual" then _[#"Team Teaching Contributor 14 allocation"] else 0
            ]
        in
            List.Sum(Record.FieldValues(CasualAllocations))
    ), 
#"Duplicated Column" = Table.DuplicateColumn(#"Added Custom 5", "Proposed Coordinator", "Proposed Coordinator - Copy"),
    #"Forecasted total course %" = Table.AddColumn(#"Duplicated Column", "Forecasted total course %", 
        each List.Sum(
            List.Select({
                [#"Proposed Coordinator - allocation"],
                [Team Teaching Contributor 1 allocation],
                [Team Teaching Contributor 2 allocation],
                [Team Teaching Contributor 3 allocation],
                [Team Teaching Contributor 4 allocation],
                [Team Teaching Contributor 5 allocation],
                [Team Teaching Contributor 6 allocation],
                [Team Teaching Contributor 7 allocation],
                [Team Teaching Contributor 8 allocation],
                [Team Teaching Contributor 9 allocation],
                [Team Teaching Contributor 10 allocation],
                [Team Teaching Contributor 11 allocation],
                [Team Teaching Contributor 12 allocation],
                [Team Teaching Contributor 13 allocation],
                [Team Teaching Contributor 14 allocation]
            }, each _ <> null)
        )
    ),
    #"Changed Type2" = Table.TransformColumnTypes(#"Forecasted total course %",{{"Forecasted total course %", type number}}),
    #"Unpivoted Only Selected Columns" = Table.Unpivot(#"Changed Type2", {"Proposed Coordinator", "Team Teaching Contributor 1", "Team Teaching Contributor 2", "Team Teaching Contributor 3", "Team Teaching Contributor 4", "Team Teaching Contributor 5", "Team Teaching Contributor 6", "Team Teaching Contributor 7", "Team Teaching Contributor 8", "Team Teaching Contributor 9", "Team Teaching Contributor 10", "Team Teaching Contributor 11", "Team Teaching Contributor 12", "Team Teaching Contributor 13", "Team Teaching Contributor 14"}, "Attribute", "Value"),
    #"Unpivoted Only Selected Columns1" = Table.Unpivot(#"Unpivoted Only Selected Columns", {"Team Teaching Contributor 14 allocation", "Team Teaching Contributor 13 allocation", "Team Teaching Contributor 12 allocation", "Team Teaching Contributor 11 allocation", "Team Teaching Contributor 10 allocation", "Team Teaching Contributor 9 allocation", "Team Teaching Contributor 8 allocation", "Team Teaching Contributor 7 allocation", "Team Teaching Contributor 6 allocation", "Team Teaching Contributor 5 allocation", "Team Teaching Contributor 4 allocation", "Team Teaching Contributor 3 allocation", "Team Teaching Contributor 2 allocation", "Team Teaching Contributor 1 allocation", "Proposed Coordinator - allocation"}, "Attribute.1", "Value.1"),
    #"Renamed Columns1" = Table.RenameColumns(#"Unpivoted Only Selected Columns1",{{"Value", "Contributing Staff"}, {"Value.1", "Allocated WL %"}}),
    #"Split Column by Delimiter" = Table.SplitColumn(#"Renamed Columns1", "Attribute.1", Splitter.SplitTextByEachDelimiter({" "}, QuoteStyle.Csv, true), {"Attribute.1.1", "Attribute.1.2"}),
    #"Split Column by Delimiter2" = Table.SplitColumn(#"Split Column by Delimiter", "Attribute.1.1", Splitter.SplitTextByEachDelimiter({" -"}, QuoteStyle.Csv, true), {"Attribute.1.1.1", "Attribute.1.1.2"}),
    #"Changed Type4" = Table.TransformColumnTypes(#"Split Column by Delimiter2",{{"Attribute.1.1.1", type text}, {"Attribute.1.1.2", type text}}),
    #"Removed Columns1" = Table.RemoveColumns(#"Changed Type4",{"Attribute.1.1.2", "Attribute.1.2"}),
    #"Added Custom6" = Table.AddColumn(#"Removed Columns1", "Custom", each if [Attribute] = [Attribute.1.1.1] then "Match" else "No Match"),
    #"Renamed Columns2" = Table.RenameColumns(#"Added Custom6",{{"Custom", "Staff and allocated the same?"}}),
    #"Added Custom7" = Table.AddColumn(#"Renamed Columns2", "Matched data", each if [#"Staff and allocated the same?"] = "Match" then [#"Allocated WL %"] else null),
    #"Added Custom8" = Table.AddColumn(#"Added Custom7", "Workload", each [Matched data]),
    #"Renamed Columns3" = Table.RenameColumns(#"Added Custom8",{{"Proposed Coordinator - Copy", "Proposed Coordinator"}, {"Matched data", "% WL"}}),
    #"Added Custom9" = Table.AddColumn(#"Renamed Columns3", "Forecasted Total WL", each [#"Forecasted total course %"]/100),
    #"Renamed Columns4" = Table.RenameColumns(#"Added Custom9",{{"Attribute.1.1.1", "Role"}}),
    #"Duplicated Column1" = Table.DuplicateColumn(#"Renamed Columns4", "Contributing Staff", "Contributing Staff - Copy"),
    #"Split Column by Delimiter1" = Table.SplitColumn(#"Duplicated Column1", "Contributing Staff - Copy", Splitter.SplitTextByEachDelimiter({"_"}, QuoteStyle.Csv, true), {"Contributing Staff Name", "Contributing Staff Number"}),
    #"Inserted Merged Column1" = Table.AddColumn(#"Split Column by Delimiter1", "Staff Key", each Text.Combine({[Contributing Staff Number], [Year]}, "_"), type text),
    #"Duplicated Column2" = Table.DuplicateColumn(#"Inserted Merged Column1", "Proposed Coordinator", "Proposed Coordinator - Copy"),
    #"Split Column by Delimiter3" = Table.SplitColumn(#"Duplicated Column2", "Proposed Coordinator", Splitter.SplitTextByEachDelimiter({"_"}, QuoteStyle.Csv, true), {"Proposed Coordinator Name", "Proposed Coordinator Number"}),
    #"Renamed Columns5" = Table.RenameColumns(#"Split Column by Delimiter3",{{"Proposed Coordinator - Copy", "Proposed Coordinator"}}),
    #"Added Custom4" = Table.AddColumn(#"Renamed Columns5", "Course Loop CC", each if [Externally Funded Coordinator] <> null and [Externally Funded Coordinator] <> "" 
then [Externally Funded Coordinator] 
else [Proposed Coordinator]),
    #"Duplicated Column3" = Table.DuplicateColumn(#"Added Custom4", "Course Loop CC", "Course Loop CC - Copy"),
    #"Split Column by Delimiter4" = Table.SplitColumn(#"Duplicated Column3", "Course Loop CC - Copy", Splitter.SplitTextByEachDelimiter({"_"}, QuoteStyle.Csv, true), {"Course Loop CC - Copy.1", "Course Loop CC - Copy.2"}),
    #"Changed Type5" = Table.TransformColumnTypes(#"Split Column by Delimiter4",{{"Proposed Coordinator Name", type text}, {"Proposed Coordinator Number", Int64.Type}, {"Contributing Staff Name", type text}, {"Contributing Staff Number", Int64.Type}, {"Course Loop CC - Copy.1", type text}, {"Course Loop CC - Copy.2", Int64.Type}}),
    #"Renamed Columns6" = Table.RenameColumns(#"Changed Type5",{{"Course Loop CC - Copy.1", "CL Course Coordinator"}, {"Course Loop CC - Copy.2", "CL Course Coordinator Number"}}),
    #"Replaced Value17" = Table.ReplaceValue(#"Renamed Columns6","GOSF","Gosford",Replacer.ReplaceText,{"Location"}),
    #"Replaced Value18" = Table.ReplaceValue(#"Replaced Value17","MID","Midyear Session",Replacer.ReplaceText,{"Term"}),
    #"Added Custom10" = Table.AddColumn(#"Replaced Value18", "Enrolment numbers", each if [Actual Census Enrols] <> null and [Actual Census Enrols] <> "" then [Actual Census Enrols] else [Forecast Enrols]),
    #"Duplicated Column4" = Table.DuplicateColumn(#"Added Custom10", "Delivery", "Delivery - Copy"),
    #"Renamed Columns7" = Table.RenameColumns(#"Duplicated Column4",{{"Delivery - Copy", "Delivery Mode"}}),
    #"Replaced Value19" = Table.ReplaceValue(#"Renamed Columns7","SIM","Simultaneous",Replacer.ReplaceText,{"Delivery Mode"}),
    #"Replaced Value20" = Table.ReplaceValue(#"Replaced Value19","OIN#(tab)","Online with Intensive",Replacer.ReplaceText,{"Delivery Mode"}),
    #"Replaced Value21" = Table.ReplaceValue(#"Replaced Value20","FLX","Flexible Online",Replacer.ReplaceText,{"Delivery Mode"}),
    #"Replaced Value22" = Table.ReplaceValue(#"Replaced Value21","F2F","Face to Face",Replacer.ReplaceText,{"Delivery Mode"}),
    #"Replaced Value23" = Table.ReplaceValue(#"Replaced Value22","MIX","Blended Learning",Replacer.ReplaceText,{"Delivery Mode"}),
    #"Replaced Value24" = Table.ReplaceValue(#"Replaced Value23","SON","Scheduled Online",Replacer.ReplaceText,{"Delivery Mode"}),
    #"Added Custom5" = Table.AddColumn(#"Replaced Value24", "WL ratio", each ([Workload]/[Forecasted Total WL])/100),
    #"Replaced Value25" = Table.ReplaceValue(#"Added Custom5",null,0,Replacer.ReplaceValue,{"WL ratio"}),
    #"Changed Type6" = Table.TransformColumnTypes(#"Replaced Value25",{{"WL ratio", type text}}),
    #"Replaced Value26" = Table.ReplaceValue(#"Changed Type6","NaN","0",Replacer.ReplaceText,{"WL ratio"}),
    #"Changed Type7" = Table.TransformColumnTypes(#"Replaced Value26",{{"WL ratio", type number}}),
    #"Rounded Off" = Table.TransformColumns(#"Changed Type7",{{"WL ratio", each Number.Round(_, 3), type number}})
in
    #"Rounded Off"