let
    Source = SharePoint.Files("https://uonstaff.sharepoint.com/sites/", [ApiVersion = 15]),
    #"Filtered Rows1" = Table.SelectRows(Source, each ([Extension] = ".xlsx") and ([Name] = "WL-PowerBI Data.xlsx")),
    #"HCISS CAL-WL-PowerBI Data xlsx_https://uonstaff sharepoint com/sites/" = #"Filtered Rows1"{[Name="WL-PowerBI Data.xlsx",#"Folder Path"="https://uonstaff.sharepoint.com/sites/"]}[Content],
    #"Imported Excel Workbook" = Excel.Workbook(#"WL-PowerBI Data xlsx_https://uonstaff sharepoint com/sites/"),
    #"course data_Sheet" = #"Imported Excel Workbook"{[Item="Course data",Kind="Sheet"]}[Data],
    #"Promoted Headers" = Table.PromoteHeaders(#"HCISS course data_Sheet", [PromoteAllScalars=true]),
    #"Replaced Value" = Table.ReplaceValue(#"Promoted Headers","NCL","Newcastle City",Replacer.ReplaceText,{"Location"}),
    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","CAL","Callaghan",Replacer.ReplaceText,{"Location"}),
    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","ONL","Online",Replacer.ReplaceText,{"Location"}),
    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","OUR","Ourimbah",Replacer.ReplaceText,{"Location"}),
    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","SEM1","Semester 1",Replacer.ReplaceText,{"Term"}),
    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","SEM2","Semester 2",Replacer.ReplaceText,{"Term"}),
    #"Replaced Value6" = Table.ReplaceValue(#"Replaced Value5","SUM2","Summer 2",Replacer.ReplaceText,{"Term"}),
    #"Replaced Value7" = Table.ReplaceValue(#"Replaced Value6","SUM1","Summer 1",Replacer.ReplaceText,{"Term"}),
    #"Replaced Value8" = Table.ReplaceValue(#"Replaced Value7","WINT","Winter",Replacer.ReplaceText,{"Term"}),
    #"Replaced Value9" = Table.ReplaceValue(#"Replaced Value8","TRI1","Trimester 1",Replacer.ReplaceText,{"Term"}),
    #"Replaced Value10" = Table.ReplaceValue(#"Replaced Value9","TRI2","Trimester 2",Replacer.ReplaceText,{"Term"}),
    #"Replaced Value11" = Table.ReplaceValue(#"Replaced Value10","TRI3","Trimester 3",Replacer.ReplaceText,{"Term"}),
    #"Replaced Value12" = Table.ReplaceValue(#"Replaced Value11","Q1","Quarter 1",Replacer.ReplaceText,{"Term"}),
    #"Replaced Value13" = Table.ReplaceValue(#"Replaced Value12","Q2","Quarter 2",Replacer.ReplaceText,{"Term"}),
    #"Replaced Value14" = Table.ReplaceValue(#"Replaced Value13","Q3","Quarter 3",Replacer.ReplaceText,{"Term"}),
    #"Replaced Value15" = Table.ReplaceValue(#"Replaced Value14","Q4","Quarter 4",Replacer.ReplaceText,{"Term"}),
    #"Changed Type3" = Table.TransformColumnTypes(#"Replaced Value15",{{"Year", type text}}),
    #"Inserted Merged Column" = Table.AddColumn(#"Changed Type3", "Key", each Text.Combine({[Course Code], [Term], [Location], [Year]}, "-"), type text),
    #"Replaced Errors1" = Table.ReplaceErrorValues(#"Inserted Merged Column", {{"% variance allocation to weighting", 0}}),
    #"Filtered Rows" = Table.SelectRows(#"Replaced Errors1", each ([Course Code] <> null)),
    #"Forecasted total course %" = Table.AddColumn(#"Filtered Rows", "Forecasted total course %", 
        each List.Sum(
            List.Select({
                [#"Proposed Coordinator - allocation"],
                [Team Teaching Contributor 1 allocation],
                [Team Teaching Contributor 2 allocation],
                [Team Teaching Contributor 3 allocation],
                [Team Teaching Contributor 4 allocation],
                [Team Teaching Contributor 5 allocation],
                [Team Teaching Contributor 6 allocation],
                [Team Teaching Contributor 7 allocation],
                [Team Teaching Contributor 8 allocation],
                [Team Teaching Contributor 9 allocation],
                [Team Teaching Contributor 10 allocation],
                [Team Teaching Contributor 11 allocation],
                [Team Teaching Contributor 12 allocation],
                [Team Teaching Contributor 13 allocation],
                [Team Teaching Contributor 14 allocation]
            }, each _ <> null)
        )
    ),
    #"Unpivoted Only Selected Columns" = Table.Unpivot(
    Table.ReplaceValue(#"Forecasted total course %", null, "No New Course developer", Replacer.ReplaceValue, {"New Course Developer 1"}), 
    {"New Course Developer 1", "New Course Developer 2", "New Course Developer 3"}, 
    "Attribute", 
    "Value"
),
    #"Unpivoted Only Selected Columns1" = Table.Unpivot(
    Table.ReplaceValue(#"Unpivoted Only Selected Columns", null, 0, Replacer.ReplaceValue, {"New Course Developer 1 allocation (up to 5 or 10%)"}), 
    {"New Course Developer 1 allocation (up to 5 or 10%)", "New Course Developer 2 allocation (up to 5 or 10%)", "New Course Developer 3 allocation (up to 5 or 10%)"}, 
    "Attribute.1", 
    "Value.1"
),
    #"Renamed Columns" = Table.RenameColumns(#"Unpivoted Only Selected Columns1",{{"Value", "New Course Developers"}, {"Value.1", "New Course Developers allocation (up to 5 or 10%)"}}),
    #"Changed Type2" = Table.TransformColumnTypes(#"Renamed Columns",{{"New Course Developers", type text},{"Attribute.1", type text}, {"New Course Developers allocation (up to 5 or 10%)", type number}}),
    #"Split Column by Delimiter" = Table.SplitColumn(#"Changed Type2", "Attribute.1", Splitter.SplitTextByDelimiter(" allocation", QuoteStyle.Csv), {"Attribute.1.1", "Attribute.1.2"}),
    #"Added Custom" = Table.AddColumn(#"Split Column by Delimiter", "Custom", each if [Attribute] = [Attribute.1.1] then "Match" else "No Match"),
    #"Removed Columns1" = Table.RemoveColumns(#"Added Custom",{"Attribute.1.2"}),
    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns1",{{"Custom", "New Course data the same?"}}),
    #"Added Custom1" = Table.AddColumn(#"Renamed Columns1", "Matched data", each if [#"New Course data the same?"] = "Match" then [#"New Course Developers allocation (up to 5 or 10%)"] else null),
    #"Added Custom2" = Table.AddColumn(#"Added Custom1", "New Course %", each [Matched data]/100),
    #"Renamed Columns2" = Table.RenameColumns(#"Added Custom2",{{"Matched data", "New Course % Match"}}),
    #"Added Custom3" = Table.AddColumn(#"Renamed Columns2", "Forecasted Total WL", each [#"Forecasted total course %"]/100),
    #"Added Custom4" = Table.AddColumn(#"Added Custom3", "Discipline", each null),
    #"Removed Columns2" = Table.RemoveColumns(#"Added Custom4",{"Forecast Course size", "Forecast Base course (value) % allocated", "Forecast overall course (value) % allocation", "% variance allocation to weighting"}),
    #"Added Conditional Column" = Table.AddColumn(#"Removed Columns2", "Forecast Course size", each if [Forecast Enrols] <= 34 then "Small" else if [Forecast Enrols] <= 74 then "Medium" else if [Forecast Enrols] <= 299 then "Large" else if [Forecast Enrols] >= 300 then "X-Large" else "Unknown"),
    #"Added Conditional Column1" = Table.AddColumn(#"Added Conditional Column", "Forecast Base course (value) % allocated", each if [#"Forecast Course size"] = "Small" then 5 else if [#"Forecast Course size"] = "Medium" then 10 else if [#"Forecast Course size"] = "Large" then 20 else if [#"Forecast Course size"] = "X-Large" then 30 else "Unknown"),
    #"Added Custom5" = Table.AddColumn(#"Added Conditional Column1", "Forecast overall course (value) % allocation", each [#"Forecast Base course (value) % allocated"]*[MULTIPLIER]),
    #"Changed Type4" = Table.TransformColumnTypes(#"Added Custom5",{{"Forecast Base course (value) % allocated", type number}, {"Forecast overall course (value) % allocation", type number}, {"% change if required at census", type number}, {"% Casual Staffing Forecast", type number}}),
    #"Duplicated Column" = Table.DuplicateColumn(#"Changed Type4", "New Course Developers", "New Course Developers - Copy"),
    #"Split Column by Delimiter1" = Table.SplitColumn(#"Duplicated Column", "New Course Developers - Copy", Splitter.SplitTextByEachDelimiter({"_"}, QuoteStyle.Csv, true), {"New Course Developers Name", "New Course Developers Number"}),
    #"Inserted Merged Column1" = Table.AddColumn(#"Split Column by Delimiter1", "Staff Key", each Text.Combine({[New Course Developers Number], [Year]}, "_"), type text),
    #"Replaced Value16" = Table.ReplaceValue(#"Inserted Merged Column1","2024","",Replacer.ReplaceValue,{"Staff Key"}),
    #"Filtered Rows2" = Table.SelectRows(#"Replaced Value16", each ([#"New Course data the same?"] = "Match")),
    #"Added Custom6" = Table.AddColumn(#"Filtered Rows2", "Course Loop CC", each if [Externally Funded Coordinator] <> null and [Externally Funded Coordinator] <> "" 
then [Externally Funded Coordinator] 
else [Proposed Coordinator]),
    #"Replaced Value17" = Table.ReplaceValue(#"Added Custom6","GOSF","Gosford",Replacer.ReplaceText,{"Location"}),
    #"Replaced Value18" = Table.ReplaceValue(#"Replaced Value17","MID","Midyear Session",Replacer.ReplaceText,{"Term"})
in
    #"Replaced Value18"